import groq from "./llm";
import { PROMPTS } from "./prompts";
import { validateAIResponse } from "./validators/responseValidator";
import { getCachedAIResponse, setCachedAIResponse } from "./cache/aiCache";
import { createCacheKey } from "./cache/cacheKey";
import { generateAnswerWithTools } from "./tools/answerWithTools";
import { AIServiceResponse } from "./aiResponseTypes";

import {
  GenerateAnswerRequest,
  ImproveQuestionRequest,
  ImproveQuestionResponse,
} from "./aiTypes";

class AIService {
  private async askAI(
    systemPrompt: string,
    userPrompt: string,
  ): Promise<string> {
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      temperature: 0.2,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
    });

    const response = completion.choices[0]?.message?.content?.trim() ?? "";
    const validation = validateAIResponse(response);

    if (!validation.valid) {
      throw new Error(validation.message);
    }

    return response;
  }

  async generateAnswer(
    data: GenerateAnswerRequest,
  ): Promise<AIServiceResponse<string>> {
    console.log("🔥 generateAnswer method reached");

    const cacheKey = createCacheKey("answer", {
      title: data.title.trim().toLowerCase(),
      description: data.description.trim().toLowerCase(),
      tags: data.tags.map((tag) => tag.trim().toLowerCase()).sort(),
    });

    const cachedAnswer = getCachedAIResponse<string>(cacheKey);

    if (cachedAnswer) {
      console.log("✅ AI Answer served from cache");

      return {
        data: cachedAnswer,
        fromCache: true,
      };
    }

    console.log("🤖 Calling Groq AI Answer with tools...");

    const answer = await generateAnswerWithTools({
      title: data.title.trim(),
      description: data.description.trim(),
      tags: data.tags.map((tag) => tag.trim().toLowerCase()),
    });

    setCachedAIResponse<string>(cacheKey, answer, 60 * 60 * 24);

    console.log("💾 AI Answer with tools generated and saved to cache");

    return {
      data: answer,
      fromCache: false,
    };
  }

  async improveQuestion(
    data: ImproveQuestionRequest,
  ): Promise<AIServiceResponse<ImproveQuestionResponse>> {
    console.log("🔥 improveQuestion method reached");

    const cacheKey = createCacheKey("improve-question", {
      title: data.title?.trim() ?? "",
      description: data.description.trim(),
    });

    const cachedResult = getCachedAIResponse<ImproveQuestionResponse>(cacheKey);

    if (cachedResult) {
      console.log("✅ Improve Question served from cache");

      return {
        data: cachedResult,
        fromCache: true,
      };
    }

    console.log("🤖 Calling Groq for Improve Question...");

    const userPrompt = `
A developer wants to improve the following programming question.

Title:
${data.title?.trim() || "No title provided"}

Description:
${data.description}

Please improve it following the system instructions.
`;

    const response = await this.askAI(PROMPTS.improveQuestion, userPrompt);

    try {
      const parsed = JSON.parse(response) as ImproveQuestionResponse;

      setCachedAIResponse<ImproveQuestionResponse>(
        cacheKey,
        parsed,
        60 * 60 * 24,
      );

      console.log("💾 Improve Question generated by Groq and saved to cache");

      return {
        data: parsed,
        fromCache: false,
      };
    } catch (error) {
      console.error("Failed to parse Improve Question AI response:", error);

      const aiError = new Error(
        "AI returned an invalid improve-question response.",
      );

      (aiError as Error & { cause?: unknown }).cause = error;

      throw aiError;
    }
  }

  async explainCode(
    code: string,
  ): Promise<AIServiceResponse<string>> {
    console.log("🔥 explainCode method reached");

    const normalizedCode = code.trim();

    const cacheKey = createCacheKey("explain-code", {
      code: normalizedCode,
    });

    const cachedExplanation = getCachedAIResponse<string>(cacheKey);

    if (cachedExplanation) {
      console.log("✅ AI Code Explanation served from cache");

      return {
        data: cachedExplanation,
        fromCache: true,
      };
    }

    console.log("🤖 Calling Groq for AI Code Explanation...");

    const userPrompt = `
Explain the following source code professionally.

Source Code:
${normalizedCode}
`;

    const explanation = await this.askAI(PROMPTS.explainCode, userPrompt);

    setCachedAIResponse<string>(
      cacheKey,
      explanation,
      60 * 60 * 24 * 7,
    );

    console.log("💾 AI Code Explanation generated by Groq and saved to cache");

    return {
      data: explanation,
      fromCache: false,
    };
  }
}

export default new AIService();