import groq from "./llm";
import { PROMPTS } from "./prompts";
import { validateAIResponse } from "./validators/responseValidator";
import { getCachedAIResponse, setCachedAIResponse } from "./cache/aiCache";
import { createCacheKey } from "./cache/cacheKey";

import {
  GenerateAnswerRequest,
  ImproveQuestionRequest,
  ImproveQuestionResponse,
} from "./aiTypes";

class AIService {
  private async askAI(
    systemPrompt: string,
    userPrompt: string,
  ): Promise<string> {
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      temperature: 0.2,
      messages: [
        {
          role: "system",
          content: systemPrompt,
        },
        {
          role: "user",
          content: userPrompt,
        },
      ],
    });

    const response = completion.choices[0]?.message?.content?.trim() ?? "";

    const validation = validateAIResponse(response);

    if (!validation.valid) {
      throw new Error(validation.message);
    }

    return response;
  }

  async generateAnswer(data: GenerateAnswerRequest): Promise<string> {
    console.log("🔥 generateAnswer method reached");

    const cacheKey = createCacheKey("answer", {
      title: data.title.trim(),
      description: data.description.trim(),
      tags: data.tags.map((tag) => tag.trim().toLowerCase()).sort(),
    });

    const cachedAnswer = getCachedAIResponse<string>(cacheKey);

    if (cachedAnswer) {
      console.log("✅ AI Answer served from cache");
      return cachedAnswer;
    }

    console.log("🤖 Calling Groq for AI Answer...");

    const userPrompt = `
A developer has posted the following programming question.

Question Title:
${data.title}

Question Description:
${data.description}

Tags:
${data.tags.length > 0 ? data.tags.join(", ") : "None"}

Please provide a helpful, accurate, and well-structured answer.

Requirements:
- Answer according to the technologies mentioned in the question and tags.
- If tags are missing, infer the technology from the title and description.
- Explain the solution clearly.
- Include code examples only when necessary.
- Recommend best practices.
- Mention common mistakes when relevant.
- If the question is ambiguous, clearly mention assumptions before answering.
`;

    const answer = await this.askAI(PROMPTS.answer, userPrompt);

    setCachedAIResponse<string>(cacheKey, answer, 60 * 60 * 24);

    console.log("💾 AI Answer generated by Groq and saved to cache");

    return answer;
  }

  async improveQuestion(
    data: ImproveQuestionRequest,
  ): Promise<ImproveQuestionResponse> {
    console.log("🔥 improveQuestion method reached");

    const cacheKey = createCacheKey("improve-question", {
      title: data.title?.trim() ?? "",
      description: data.description.trim(),
    });

    const cachedResult = getCachedAIResponse<ImproveQuestionResponse>(cacheKey);

    if (cachedResult) {
      console.log("✅ Improve Question served from cache");
      return cachedResult;
    }

    console.log("🤖 Calling Groq for Improve Question...");

    const userPrompt = `
A developer wants to improve the following programming question.

Title:
${data.title?.trim() || "No title provided"}

Description:
${data.description}

Please improve it following the system instructions.
`;

    const response = await this.askAI(PROMPTS.improveQuestion, userPrompt);

    try {
      const parsed = JSON.parse(response) as ImproveQuestionResponse;

      setCachedAIResponse<ImproveQuestionResponse>(
        cacheKey,
        parsed,
        60 * 60 * 24,
      );

      console.log("💾 Improve Question generated by Groq and saved to cache");

      return parsed;
    } catch (error) {
      console.error("Failed to parse Improve Question AI response:", error);

      const aiError = new Error(
        "AI returned an invalid improve-question response.",
      );

      (aiError as Error & { cause?: unknown }).cause = error;

      throw aiError;
    }
  }

  // async generateTitle(description: string): Promise<string> {
  //   return this.askAI(PROMPTS.generateTitle, description);
  // }

  // async generateTags(description: string): Promise<string> {
  //   return this.askAI(PROMPTS.generateTags, description);
  // }

  async explainCode(code: string): Promise<string> {
    console.log("🔥 explainCode method reached");

    const normalizedCode = code.trim();

    const cacheKey = createCacheKey("explain-code", {
      code: normalizedCode,
    });

    const cachedExplanation = getCachedAIResponse<string>(cacheKey);

    if (cachedExplanation) {
      console.log("✅ AI Code Explanation served from cache");
      return cachedExplanation;
    }

    console.log("🤖 Calling Groq for AI Code Explanation...");

    const userPrompt = `
      Explain the following source code professionally.

      Source Code:
      ${normalizedCode}
      `;

    const explanation = await this.askAI(PROMPTS.explainCode, userPrompt);

    setCachedAIResponse<string>(cacheKey, explanation, 60 * 60 * 24 * 7);

    console.log("💾 AI Code Explanation generated by Groq and saved to cache");

    return explanation;
  }
}

export default new AIService();
